// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type LikedSong struct {
	ID     uuid.UUID
	UserID uuid.UUID
	SongID uuid.UUID
}

type Song struct {
	ID       uuid.UUID
	Name     string
	SongLink string
	UserID   uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Username       string
	Password       string
	RefreshToken   sql.NullString
	ProfilePicture sql.NullString
}
